### ISSUE TITLE
Documentation poor, esp. on script parameters

### ISSUE THREAD

**Issue by craigemery** [jenkinsci/jenkins-scripts#112]
Please ignore this, raised in error

**Comment by craigemery** [comment]
This v 2.9.

**Comment by craigemery** [comment]
```
10:41:34 Execution of script [triggerNextBuildNum.groovy] failed - groovy.lang.MissingPropertyException: No such property: NAMESPACE for class: Script1org.jenkinsci.plugins.scriptler.util.GroovyScript$ScriptlerExecutionException: groovy.lang.MissingPropertyException: No such property: NAMESPACE for class: Script1
10:41:34 	at org.jenkinsci.plugins.scriptler.util.GroovyScript.call(GroovyScript.java:131)
10:41:34 	at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
10:41:34 	at org.jenkinsci.plugins.scriptler.builder.ScriptlerBuilder.perform(ScriptlerBuilder.java:114)
10:41:34 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
10:41:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
10:41:34 	at hudson.model.Build$BuildExecution.build(Build.java:206)
10:41:34 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
10:41:34 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
10:41:34 	at hudson.model.Run.execute(Run.java:1724)
10:41:34 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
10:41:34 	at hudson.model.ResourceController.execute(ResourceController.java:97)
10:41:34 	at hudson.model.Executor.run(Executor.java:429)
10:41:34 Caused by: groovy.lang.MissingPropertyException: No such property: NAMESPACE for class: Script1
10:41:34 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
10:41:34 	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
10:41:34 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
10:41:34 	at Script1.run(Script1.groovy:23)
10:41:34 	at org.jenkinsci.plugins.scriptler.util.GroovyScript.call(GroovyScript.java:122)
10:41:34 	... 11 more
10:41:34 Build step 'Scriptler script' marked build as failure

```

**Comment by craigemery** [comment]
Oops. I think I've confused your scriptler
