### ISSUE TITLE
hashifyAllScmTriggers fail on ExternalJob

### ISSUE THREAD

**Issue by francisoud** [jenkinsci/jenkins-scripts#48]
hashifyAllScmTriggers fail on ExternalJob
```
ERROR: Build step failed with exception
groovy.lang.MissingMethodException: No signature of method: hudson.model.ExternalJob.getTriggers() is applicable for argument types: () values: []
Possible solutions: getWidgets()
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:55)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:42)
	at jenkins.model.ParameterizedJobMixIn$ParameterizedJob$getTriggers.call(Unknown Source)
	at Script1.run(Script1.groovy:21)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:650)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:636)
	at hudson.plugins.groovy.SystemGroovy.perform(SystemGroovy.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Execute system Groovy script' marked build as failure
```
I'll provide a PR

**Comment by imod** [comment]
merged with 9f3846c5f7622a84d588a53bea9b00c0df7b682a
