### ISSUE TITLE
hashifyAllScmTriggers incompatibility with Jenkins ver. 2.0

### ISSUE THREAD

**Issue by francisoud** [jenkinsci/jenkins-scripts#63]
https://github.com/jenkinsci/jenkins-scripts/blob/master/scriptler/hashifyAllScmTriggers.groovy
is incompatible with Jenkins ver. 2.0

```
ERROR: Build step failed with exception
groovy.lang.MissingPropertyException: No such property: scm for class: org.jenkinsci.plugins.workflow.job.WorkflowJob
Possible solutions: SCMs, ACL, url, name, api
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.getProperty(GetEffectivePojoPropertySite.java:66)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
	at Script1$_run_closure4.doCall(Script1.groovy:39)
	at sun.reflect.GeneratedMethodAccessor742.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:51)
	at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:53)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4281)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4153)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4138)
	at org.codehaus.groovy.runtime.dgm$202.invoke(Unknown Source)

```

**Comment by francisoud** [comment]
See merge request: https://github.com/jenkinsci/jenkins-scripts/pull/65
